export const WS_USERFEED_CONNECTION_ERROR:"WS_USERFEED_CONNECTION_ERROR" = "WS_USERFEED_CONNECTION_ERROR";
export const WS_USERFEED_CONNECTION_START:"WS_USERFEED_CONNECTION_START" = "WS_USERFEED_CONNECTION_START";
export const WS_USERFEED_CLOSE_CONNECTION:"WS_USERFEED_CLOSE_CONNECTION" = "WS_USERFEED_CLOSE_CONNECTION";
export const WS_USERFEED_CONNECTION_SUCCESS:"WS_USERFEED_CONNECTION_SUCCESS" = "WS_USERFEED_CONNECTION_SUCCESS";
export const WS_USERFEED_CONNECTION_CLOSED:"WS_USERFEED_CONNECTION_CLOSED" = "WS_USERFEED_CONNECTION_CLOSED";
export const WS_USERFEED_GET_ORDERS:"WS_USERFEED_GET_ORDERS" = "WS_USERFEED_GET_ORDERS";
